version: '3'
services:
  database:
    image: mariadb
    restart: always
    env_file:
      - api/.env
    volumes:
      - dbdata:/var/lib/mysql/data
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080
  api:
    build: ./api
    env_file:
      - api/.env
    volumes:
      - ./api:/usr/src/api/
      - /usr/src/api/node_modules
    links:
      - database
    depends_on:
      - rabbitmq
      - database
  nginx:
    restart: always
    build: ./nginx
    ports:
      - '5000:80'
    depends_on:
      - api
      - database
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    environment:
      - AMQP_HOST='host.docker.internal'
    ports:
      - 5672:5672
      - 15672:15672
volumes:
  dbdata:
