name: Deploy to DigitalOcean Droplet

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
        
    - name: Deploy to Droplet
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DROPLET_IP }}
        username: ${{ secrets.DROPLET_USERNAME }}
        key: ${{ secrets.DROPLET_KEY }}
        port: ${{ secrets.DROPLET_PORT }}
        script: |
          cd /back-end
          docker-compose build
          docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d
